// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa8Bukpp12S1imV-E0EHY_okDhaiTCT1o',
    appId: '1:438152716054:web:44c4b288bc6a8ebddf3a37',
    messagingSenderId: '438152716054',
    projectId: 'fitfoot',
    authDomain: 'fitfoot.firebaseapp.com',
    storageBucket: 'fitfoot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7y2ZeZnGWRB3iwrYtptcChCPV1RdvNIk',
    appId: '1:438152716054:android:a6e07923a7b4550adf3a37',
    messagingSenderId: '438152716054',
    projectId: 'fitfoot',
    storageBucket: 'fitfoot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIfXpTQz5C-UEHirp6m2_Wd-04-6iJXBw',
    appId: '1:438152716054:ios:e59083519355f16ddf3a37',
    messagingSenderId: '438152716054',
    projectId: 'fitfoot',
    storageBucket: 'fitfoot.appspot.com',
    iosClientId: '438152716054-je6141vmh1tsehnc24i0d2s0e59n3sae.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitfoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIfXpTQz5C-UEHirp6m2_Wd-04-6iJXBw',
    appId: '1:438152716054:ios:e59083519355f16ddf3a37',
    messagingSenderId: '438152716054',
    projectId: 'fitfoot',
    storageBucket: 'fitfoot.appspot.com',
    iosClientId: '438152716054-je6141vmh1tsehnc24i0d2s0e59n3sae.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitfoot',
  );
}
